import type { FamilyTree } from "./types"

export type TemplateType = "family-tree" | "mind-map" | "org-chart" | "timeline"

export interface Template {
  id: TemplateType
  name: string
  description: string
  icon: string
  tree: Omit<FamilyTree, "id" | "createdAt" | "updatedAt">
}

export const TEMPLATES: Template[] = [
  {
    id: "family-tree",
    name: "Family Tree",
    description: "A classic multi-generational family tree layout",
    icon: "👨‍👩‍👧‍👦",
    tree: {
      name: "My Family Tree",
      nodes: [
        {
          id: "node-1",
          name: "John Doe",
          relationship: "parent",
          x: 400,
          y: 50,
          width: 150,
          height: 80,
          notes: "Family patriarch",
          birthYear: 1945,
          gender: "male",
        },
        {
          id: "node-2",
          name: "Jane Doe",
          relationship: "spouse",
          x: 600,
          y: 50,
          width: 150,
          height: 80,
          notes: "Family matriarch",
          birthYear: 1947,
          gender: "female",
        },
        {
          id: "node-3",
          name: "Mark Doe",
          relationship: "child",
          x: 300,
          y: 200,
          width: 150,
          height: 80,
          notes: "Eldest son",
          birthYear: 1970,
          gender: "male",
        },
        {
          id: "node-4",
          name: "Sarah Doe",
          relationship: "child",
          x: 500,
          y: 200,
          width: 150,
          height: 80,
          notes: "Younger daughter",
          birthYear: 1975,
          gender: "female",
        },
        {
          id: "node-5",
          name: "Emma Smith",
          relationship: "spouse",
          x: 700,
          y: 200,
          width: 150,
          height: 80,
          notes: "Mark's wife",
          birthYear: 1972,
          gender: "female",
        },
      ],
      connections: [
        { id: "conn-1", sourceId: "node-1", targetId: "node-3", type: "parent-child" },
        { id: "conn-2", sourceId: "node-1", targetId: "node-4", type: "parent-child" },
        { id: "conn-3", sourceId: "node-2", targetId: "node-3", type: "parent-child" },
        { id: "conn-4", sourceId: "node-2", targetId: "node-4", type: "parent-child" },
        { id: "conn-5", sourceId: "node-1", targetId: "node-2", type: "spouse" },
        { id: "conn-6", sourceId: "node-3", targetId: "node-5", type: "spouse" },
      ],
    },
  },
  {
    id: "mind-map",
    name: "Mind Map",
    description: "Brainstorming and idea organization",
    icon: "🧠",
    tree: {
      name: "Mind Map",
      nodes: [
        {
          id: "node-1",
          name: "Central Idea",
          relationship: "parent",
          x: 400,
          y: 200,
          width: 150,
          height: 80,
          notes: "Main concept",
        },
        {
          id: "node-2",
          name: "Topic 1",
          relationship: "child",
          x: 100,
          y: 100,
          width: 150,
          height: 80,
          notes: "First branch",
        },
        {
          id: "node-3",
          name: "Topic 2",
          relationship: "child",
          x: 100,
          y: 200,
          width: 150,
          height: 80,
          notes: "Second branch",
        },
        {
          id: "node-4",
          name: "Topic 3",
          relationship: "child",
          x: 100,
          y: 300,
          width: 150,
          height: 80,
          notes: "Third branch",
        },
        {
          id: "node-5",
          name: "Topic 4",
          relationship: "child",
          x: 700,
          y: 150,
          width: 150,
          height: 80,
          notes: "Fourth branch",
        },
        {
          id: "node-6",
          name: "Topic 5",
          relationship: "child",
          x: 700,
          y: 250,
          width: 150,
          height: 80,
          notes: "Fifth branch",
        },
      ],
      connections: [
        { id: "conn-1", sourceId: "node-1", targetId: "node-2", type: "parent-child" },
        { id: "conn-2", sourceId: "node-1", targetId: "node-3", type: "parent-child" },
        { id: "conn-3", sourceId: "node-1", targetId: "node-4", type: "parent-child" },
        { id: "conn-4", sourceId: "node-1", targetId: "node-5", type: "parent-child" },
        { id: "conn-5", sourceId: "node-1", targetId: "node-6", type: "parent-child" },
      ],
    },
  },
  {
    id: "org-chart",
    name: "Organization Chart",
    description: "Company hierarchy and team structure",
    icon: "🏢",
    tree: {
      name: "Organization Chart",
      nodes: [
        {
          id: "node-1",
          name: "CEO",
          relationship: "parent",
          x: 400,
          y: 20,
          width: 150,
          height: 80,
          notes: "Chief Executive Officer",
        },
        {
          id: "node-2",
          name: "VP Engineering",
          relationship: "child",
          x: 150,
          y: 150,
          width: 150,
          height: 80,
          notes: "Engineering Lead",
        },
        {
          id: "node-3",
          name: "VP Sales",
          relationship: "child",
          x: 400,
          y: 150,
          width: 150,
          height: 80,
          notes: "Sales Lead",
        },
        {
          id: "node-4",
          name: "VP Marketing",
          relationship: "child",
          x: 650,
          y: 150,
          width: 150,
          height: 80,
          notes: "Marketing Lead",
        },
        {
          id: "node-5",
          name: "Team Lead",
          relationship: "child",
          x: 100,
          y: 280,
          width: 150,
          height: 80,
          notes: "Backend Team",
        },
        {
          id: "node-6",
          name: "Team Lead",
          relationship: "child",
          x: 250,
          y: 280,
          width: 150,
          height: 80,
          notes: "Frontend Team",
        },
      ],
      connections: [
        { id: "conn-1", sourceId: "node-1", targetId: "node-2", type: "parent-child" },
        { id: "conn-2", sourceId: "node-1", targetId: "node-3", type: "parent-child" },
        { id: "conn-3", sourceId: "node-1", targetId: "node-4", type: "parent-child" },
        { id: "conn-4", sourceId: "node-2", targetId: "node-5", type: "parent-child" },
        { id: "conn-5", sourceId: "node-2", targetId: "node-6", type: "parent-child" },
      ],
    },
  },
  {
    id: "timeline",
    name: "Timeline",
    description: "Historical events and chronological order",
    icon: "📅",
    tree: {
      name: "Timeline",
      nodes: [
        {
          id: "node-1",
          name: "Event 1",
          relationship: "parent",
          x: 100,
          y: 150,
          width: 150,
          height: 80,
          notes: "Year 2020",
          birthYear: 2020,
        },
        {
          id: "node-2",
          name: "Event 2",
          relationship: "child",
          x: 300,
          y: 150,
          width: 150,
          height: 80,
          notes: "Year 2021",
          birthYear: 2021,
        },
        {
          id: "node-3",
          name: "Event 3",
          relationship: "child",
          x: 500,
          y: 150,
          width: 150,
          height: 80,
          notes: "Year 2022",
          birthYear: 2022,
        },
        {
          id: "node-4",
          name: "Event 4",
          relationship: "child",
          x: 700,
          y: 150,
          width: 150,
          height: 80,
          notes: "Year 2023",
          birthYear: 2023,
        },
      ],
      connections: [
        { id: "conn-1", sourceId: "node-1", targetId: "node-2", type: "parent-child" },
        { id: "conn-2", sourceId: "node-2", targetId: "node-3", type: "parent-child" },
        { id: "conn-3", sourceId: "node-3", targetId: "node-4", type: "parent-child" },
      ],
    },
  },
]
